### PR TITLE
Dst wip

### PR DESCRIPTION
**Pull request by steveshogren**

### CODE REVIEW

**Comment by steveshogren** [comment]
Wow, you really got into it with both hands!

I dig a lot of the changes made. 

I'm "meh" on merging commands and queries, I like to keep them separate, but it's harmless. 

I can put in the logic for the TODO's you left in. There are tests, all of which are still passing, I'm not sure if that was by accident, but good job on that. I'll add more for the update-all-students-from-dst function.

Also, thanks for namespacing the un-namespaced tables I missed. 

For "not knowing clojure" you sure figured out a lot anyway, good job!

If you add my public key I'll push some thoughts that might help.

**Comment by schmave** [comment]
Hey there! Yeah I jumped in and tore it apart. Feel free to tweak my code and fix style issues. I combined "queries" and "commands" because I thought it was necessary in order to call functions in "queries" from "commands", but now I look and see that you were already doing that, so maybe I was just confused in the moment. 

If you want to finish up those TODOs that would be great!

I've added your public key to the server so you should be able to `make deploy-dst`

**Comment by steveshogren** [comment]
Could you add me to have access to push to your git fork? I cannot change the PR without it.

**Comment by schmave** [comment]
Yup, you should have an invite from GH

**Comment by schmave** [comment]
So that you know, DST makes a request to /updatefromdst whenever you change the attendance settings on the settings page, add or remove a tag from a person, or edit a person's information.

**Pull request merged**
