### PR TITLE
Fix bugs in syncing from DST

### PR DESCRIPTION
**Pull request by schmave**

### CODE REVIEW

**Comment by schmave** [comment]
(This is live on custodia.demschooltools.com)

**Comment by steveshogren** [comment]
This PR fundamentally breaks Custodia unless it is running with DST. I am of two minds about this. One, if I decide this is acceptable, I am not sure if it should still live alone in a repo without DST. I don't think it makes any sense to have a project that does not function standalone to be in a repo alone. Two, if I decide to allow Custodia to function alone without DST (so if you ever tire of supporting DST I can continue to support Custodia in your absence) then I am left supporting (and testing) two increasingly different versions of Custodia. Also, since PFS is the only school that was using Custodia (and they are now using the hybrid) I'd be testing and supporting a version not in production anywhere. 

I am not super thrilled with either solution. Let me ponder on this further.

**Comment by schmave** [comment]
Yeah, I guess this needs to be figured out. You could have it so that this repo doesn't have DST-specific stuff in it, and I maintain a fork in schmave/overseer that has all the DST stuff. Sounds like you are well aware of the options. Let me know what you decide.

**Comment by steveshogren** [comment]
For now I've added a toggle for dst mode, and I'll ponder further a long-term merge.

**Comment by steveshogren** [comment]
Since right now the biggest change is cosmetic, I'll maintain the separation. It makes my testing burden lighter as I don't need to run a whole instance of DST just to manually test Custodia. 

You'll need to set the "dst-mode" field in your environment to true if you want to disable those two create buttons. Otherwise it should all be the same.

**Comment by schmave** [comment]
OK, sounds good! We'll try this for a bit.

**Pull request merged**
