### PR TITLE
Various bug fixes

### LINKED ISSUE #59: Class late_time not expressed in school's time zone
The `late_time` column in the `classes` table is interpreted as a time in the server's local timezone. In my case, this is UTC, so if a school in EST has a late time of 10:15 (school local time), I can put 15:15 (server local time) in the `classes` table and it works. However, when daylight savings time comes back I'll have to change 15:15 to 14:15. So there is four months until this is particularly annoying :)

### PR DESCRIPTION
**Pull request by schmave**
I do most of my testing after 8pm, which is the next day in UTC, and thus swiping in and out barely works. I got a bit carried away fixing all the bugs that prevent me from testing. (I also disabled swipe rounding in my fork, because that makes the site unusable outside of the hours of 9-4, which again is when I do most of my testing). 

There are still React warnings on the main page, but not on the student page anymore. 

Closes #59

### CODE REVIEW

**Comment by schmave** [comment]
Three improvements in functionality: 
* Order swipes on detail page by "in" time
* Allow use of local time for classes.late_time
* Make late highlighting use the first "in" of the day, not the last

**Comment by steveshogren** [comment]
I noticed that this broke some tests, I'll look at them tonight and try to fix them.

**Comment by steveshogren** [comment]
I think it may have messed up the "required_minutes" showing on the student when he has no minutes set but the class does. As such I wouldn't deploy it until its sorted out.

**Comment by schmave** [comment]
Hmmm. I think that the trouble is that the test is retrieving the student
before adding them to the class that has a required_minutes, so then the
student's required_minutes is nil because it is not associated with a
class. After adding the student to the class, the required_minutes is set
properly.

**Comment by steveshogren** [comment]
Yep, good catch. The other test was a real issue with the query, but I sorted it out and explained it in the commit.

**Comment by schmave** [comment]
Great!

**Pull request merged**
